baseurl = "http://hbkr.github.io/"
languageCode = "ja"
title = "KAZUMA IEIRI"
theme = "habakarizm"

[Params]
subtitle = "I LOVE INTERNET"
facebook = "https://facebook.com/ieiri"
twitter = "https://twitter.com/hbkr"
github = "https://github.com/hbkr"
profile = ""
copyright = "Written by Kazuma Ieiri"
analytics = ""

