baseurl = "http://hbkr.github.io/"
languageCode = "ja"
title = "KAZUMA IEIRI"
theme = "habakarizm"
hasCJKLanguage = true
Paginate = 10

[taxonomies]
category = "categories"
tag = "tags"

[params]
subtitle = "I LOVE INTERNET"
facebook = "https://facebook.com/ieiri"
twitter = "https://twitter.com/hbkr"
github = "https://github.com/hbkr"
profile = ""
copyright = "Written by Kazuma Ieiri"
analytics = ""
author = "Kazuma Ieiri"

